export const GET_COMPONENTS = 'GET_COMPONENTS';

export const UPDATE_CANVAS_STATE = 'UPDATE_CANVAS_STATE';
export const UPDATE_RIGHT_BAR = 'UPDATE_RIGHT_BAR';

export const CANVAS_MESSAGE_UPDATE = 'CANVAS_MESSAGE_UPDATE';
